### ISSUE TITLE
9. As a development team we would like to provide the data analysts with information about the number of people who speak Spanish, English, Hindi, Arabic and Chinese in ascending order including the percentage of the world population so that it can be used for analysis about the most spoken language.

### ISSUE THREAD

**Issue by omonimus1** [omonimus1/SEM_group_project#49]
Provide the number of people who speak the following the following languages from greatest number to smallest, including the percentage of the world population:

* Chinese.
* English.
* Hindi.
* Spanish.
* Arabic.

**Comment by omonimus1** [comment]
Updated issue name to add consistency in Pratical Labs

**Comment by McPenquen** [comment]
So here is an SQL query for it (however it assumes that the world's population is 6 078 749 450) : 
    SELECT countrylanguage.Language,
    ROUND(SUM(country.Population * (countrylanguage.Percentage/100))) AS `People Speaking`,
    CONCAT(ROUND((SUM(country.Population * (countrylanguage.Percentage/100))/6078749450) * 100,3),'%') AS `World Percantage`
    FROM countrylanguage JOIN country ON (countrylanguage.CountryCode = country.Code)
        GROUP BY countrylanguage.Language
    HAVING countrylanguage.Language = 'English'
    OR countrylanguage.Language = 'Chinese'
    OR countrylanguage.Language = 'Hindi'
    OR countrylanguage.Language = 'Spanish'
    OR countrylanguage.Language = 'Arabic'
    ORDER BY ROUND(SUM(country.Population * (countrylanguage.Percentage/100))) DESC;

**Comment by McPenquen** [comment]
OK I have abetter version!!!!
VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV
    SELECT countrylanguage.Language,
    ROUND(SUM(country.Population * (countrylanguage.Percentage/100))) AS `People Speaking`,
    CONCAT(ROUND((SUM(country.Population * (countrylanguage.Percentage/100))/(SELECT SUM(country.Population) FROM country)) * 100,3),'%') AS `World Percantage`
    FROM countrylanguage JOIN country ON (countrylanguage.CountryCode = country.Code)
    WHERE countrylanguage.Language = 'English'
    OR countrylanguage.Language = 'Chinese'
    OR countrylanguage.Language = 'Hindi'
    OR countrylanguage.Language = 'Spanish'
    OR countrylanguage.Language = 'Arabic'
    GROUP BY countrylanguage.Language
    ORDER BY ROUND(SUM(country.Population * (countrylanguage.Percentage/100))) DESC;

**Comment by McPenquen** [comment]
*Supposed to be ASC not DESC

**Comment by McPenquen** [comment]
*so it's DESC not ASC at the end _:D
