### ISSUE TITLE
6. As a Data Analyst I want to generate reports on the top X populated capital cities in the world, in a continent and in a region, where X is a number provided by me, so that a statistical report for the most populated capital city can be made.

### ISSUE THREAD

**Issue by McPenquen** [omonimus1/SEM_group_project#60]

**Comment by omonimus1** [comment]
* The top N populated capital cities in the world where N is provided by the user.
* The top N populated capital cities in a continent where N is provided by the user.
* The top N populated capital cities in a region where N is provided by the user.
